######################################################################
# Automatically generated by qmake (3.0) Wed May 6 17:44:11 2020
######################################################################

TEMPLATE = app
TARGET = TestSample
INCLUDEPATH += .

# Input
SOURCES += testmain.cpp
QT += gui widgets

